description = "Communauté francophone de psychologie moderne"
tagline = "Explorer, comprendre, partager"
heroImage = "/images/hero/default.jpg"

[contact]
  email = "contact@neurau.eu"

goatcounter = "neurau"
isso = "https://comments.neurau.eu/"

[social]
  facebook = ""
  instagram = ""
  linkedin = ""
