description = "Communauté francophone de psychologie moderne"
tagline = "Explorer, comprendre, partager"
isso = "/.comments/"

[contact]
  email = "contact@neurau.eu"

[social]
  facebook = ""
  instagram = ""
  linkedin = ""
